package com.mdmp.infra.rule
 
import com.mdmp.infra.message.JsonMessage;

rule "Add"
    when
        m : JsonMessage(status < 0 )
    then
        System.out.println( "Rule: Add" );
        System.out.println( "Message status:" + m.getStatus());
        Integer age = Integer.valueOf((String)m.getValue("age"));
        age += 10;
        m.putValue("age", age.toString());
        //update( m );
        m.setStatus(0);
end

